import pandas as pd
import plotly.express as px
from jinja2 import Template
import datetime
import os

def generate_html_report():
    # Load the CSV generated by fetch_ado_data.py
    df = pd.read_csv("output/sprint_data.csv")

    # Calculate metrics
    status_counts = df['State'].value_counts().to_dict()
    assigned_counts = df['Assignee'].value_counts().to_dict()

    # Create a bar chart for status breakdown using Plotly
    fig_status = px.bar(
        x=list(status_counts.keys()),
        y=list(status_counts.values()),
        labels={'x': 'State', 'y': 'Count'},
        title="Story Status Breakdown"
    )
    os.makedirs("output", exist_ok=True)
    fig_status.write_html("output/status_chart.html", include_plotlyjs='cdn')

    # Load the Jinja2 HTML template
    with open("templates/dashboard_template.html") as f:
        template = Template(f.read())

    html_out = template.render(
        generated_on=str(datetime.datetime.now()),
        status_chart="status_chart.html",
        assigned=assigned_counts,
        status_counts=status_counts
    )

    # Write the final HTML report
    os.makedirs("output", exist_ok=True)
    with open("output/sprint_report.html", "w") as out:
        out.write(html_out)

    print("✅ Dashboard generated at output/sprint_report.html")

if __name__ == "__main__":
    generate_html_report()
